apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: example-resource
  annotations:
    github.com/project-slug: susanta2022/example-resource
spec:
  type: other
  lifecycle: unknown
  owner: guests
